aliases:
  - &testing_xcode
    os: osx
    language: objective-c
    install:
      - ./scripts/install_swiftlint.sh
    script:
      - set -o pipefail
      - xcodebuild build-for-testing test-without-building -workspace Carbon.xcworkspace -scheme Carbon -configuration Release -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X' ENABLE_TESTABILITY=YES | xcpretty - c

matrix:
  include:
    - <<: *testing_xcode
      osx_image: xcode10.1

    - <<: *testing_xcode
      osx_image: xcode10.2

notifications:
  email: false
